### ISSUE TITLE
Random crash on startup (while restoring fallback queue)

### ISSUE THREAD

**Issue by brainexe** [innogames/slack-bot#29]
I noticed a random crash in booting process while processing the fallback queue: 
```
Oct  2 11:22:49 slack-bot slack-bot[12008]: time="2020-10-02T11:22:49Z" level=info msg="[Queue] Booted! I'll trigger this command now: `<https://bitbucket.XXXXX.de/projects/fooobarr/pull-requests/14015/overview> please take a look in this crazy pull request`"
Oct  2 11:22:49 slack-bot slack-bot[12008]: time="2020-10-02T11:22:49Z" level=info msg="Connecting to slack..."
Oct  2 11:22:52 slack-bot slack-bot[12008]: time="2020-10-02T11:22:52Z" level=info msg="Loaded 39 allowed users and 1315 channels"
Oct  2 11:22:52 slack-bot slack-bot[12008]: time="2020-10-02T11:22:52Z" level=info msg="bot user: foe_bot with ID: U2HUK5490"
Oct  2 11:22:52 slack-bot slack-bot[12008]: time="2020-10-02T11:22:52Z" level=info msg="Initialized 30 commands"
Oct  2 11:22:52 slack-bot slack-bot[12008]: panic: runtime error: invalid memory address or nil pointer dereference
Oct  2 11:22:52 slack-bot slack-bot[12008]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8533d3]
Oct  2 11:22:52 slack-bot slack-bot[12008]: goroutine 93 [running]:
Oct  2 11:22:52 slack-bot slack-bot[12008]: github.com/innogames/slack-bot/bot.(*Commands).Run(0xc000075b80, 0xc000027680, 0x24, 0xc0002664a0, 0x7, 0xc0002664a7, 0x9, 0xc0002664b0, 0x9, 0xc00021ce70, ...)
Oct  2 11:22:52 slack-bot slack-bot[12008]: #011/Users/XXXX/Projects/slack-bot/bot/command.go:50 +0x93
Oct  2 11:22:52 slack-bot slack-bot[12008]: github.com/innogames/slack-bot/bot.bot.handleMessage(0xc0000267b0, 0x29, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc000021770, ...)
Oct  2 11:22:52 slack-bot slack-bot[12008]: #011/Users/XXXX/Projects/slack-bot/bot/bot.go:254 +0x3b8
Oct  2 11:22:52 slack-bot slack-bot[12008]: created by github.com/innogames/slack-bot/bot.bot.HandleMessages
Oct  2 11:22:52 slack-bot slack-bot[12008]: #011/Users/XXX/Projects/slack-bot/bot/bot.go:188 +0x59b
Oct  2 11:22:52 slack-bot systemd[1]: slack-bot.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct  2 11:22:52 slack-bot systemd[1]: slack-bot.service: Failed with result 'exit-code'.
Oct  2 11:22:53 slack-bot systemd[1]: slack-bot.service: Service RestartSec=100ms expired, scheduling restart.
Oct  2 11:22:53 slack-bot systemd[1]: slack-bot.service: Scheduled restart job, restart counter is at 1.

```
-> tries to process commands before bot object got initialized.

**Idea:** 
- handle the startup queue queue a delay when everything is established
- handle fallback queue sequentially

**Comment by brainexe** [comment]
*Reason:* Command.compile was called in parallel which created a broken state

Now added a proper lock and also made all tests pass with "-race"
